### ISSUE TITLE
cannot add or modify more than 10 variables in config

### ISSUE THREAD

**Issue by sannithibalaji** [GetSimpl/cloudlift#32]
boto throw's error of max limit reached incase we modify more than 10 variables, code should internally make multiple API calls to overcome this limit.

**Comment by shoan** [comment]
Thanks for your report. Please provide more information. Which cloudlift command? What 10 variables?

**Comment by sannithibalaji** [comment]
in cloud lift command edit_config, it opens up an editor to update env variables which internally updates it to parameter store.
AWS boto SDK is raising an exception if we update more than 10 env variables in edit_config file.

**Comment by shoan** [comment]
I just added 100 parameters to a service with no issues. Can you share the stacktrace and exception?

**Comment by sannithibalaji** [comment]
Traceback (most recent call last):
  File "/usr/local/bin/cloudlift", line 11, in <module>
    load_entry_point('cloudlift==1.4.3', 'console_scripts', 'cloudlift')()
  File "/root/rippling/cloudlift/venv/lib/python3.7/site-packages/cloudlift-1.4.3-py3.7.egg/cloudlift/__init__.py", line 43, in __call__
  File "/root/rippling/cloudlift/venv/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/root/rippling/cloudlift/venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/rippling/cloudlift/venv/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/rippling/cloudlift/venv/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/root/rippling/cloudlift/venv/lib/python3.7/site-packages/cloudlift-1.4.3-py3.7.egg/cloudlift/__init__.py", line 37, in wrapper
  File "/root/rippling/cloudlift/venv/lib/python3.7/site-packages/cloudlift-1.4.3-py3.7.egg/cloudlift/__init__.py", line 26, in wrapper
  File "/root/rippling/cloudlift/venv/lib/python3.7/site-packages/cloudlift-1.4.3-py3.7.egg/cloudlift/__init__.py", line 101, in edit_config
  File "/root/rippling/cloudlift/venv/lib/python3.7/site-packages/cloudlift-1.4.3-py3.7.egg/cloudlift/deployment/editor.py", line 28, in edit_config
  File "/root/rippling/cloudlift/venv/lib/python3.7/site-packages/cloudlift-1.4.3-py3.7.egg/cloudlift/config/parameter_store.py", line 80, in set_config
  File "/root/rippling/cloudlift/venv/lib/python3.7/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/root/rippling/cloudlift/venv/lib/python3.7/site-packages/botocore/client.py", line 635, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the DeleteParameters operation: 1 validation error detected: Value '[*******************************************]' at 'names' failed to satisfy constraint: Member must have length less than or equal to 10

**Comment by sannithibalaji** [comment]
sorry, for wrong info, i am not able to delete more than 10 at once.

**Comment by sannithibalaji** [comment]
@shoan
